language: scala
scala:
- 2.12.8
- 2.13.0
install:
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.4.9
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt ++$TRAVIS_SCALA_VERSION clean coverageOff compile publish; };'
env:
  global:
  - secure: oDETeu+DVmy7KkoCqA658ZbDIYmsIx2lRBkclJh17AeHIiCnYasFGRDnDqZKEqqIfpHwUNBGIua3xe6+GRwBJwqZH3cnJVDUNMAgMp93bznvXAFEm2C0wixaXGz9tAdFMbEwVq57eW0TapiIKyx8VvLDybs9WsTh330qrqhttrWV6BUnMjlR4ULd6vyIXlijaO93s8LxgJPT1ogYetvUKqv89NmshA/BwTgYLv1MVYKcpPO+jIOQS3nMnULiI6MMIh2OLVnXBUXQx6f5dg+FzRMuCOJ5pZZxoFfjpA4wH6A+e4hVbBcpAvgkj1yuEPPvjF7EyjqeVDLbffpESJRGnFyaP6jDa4JJQY5QS8MbJJU3EqnD7gOl6xhOzdT5ilabYg7GCRAX/Ve+6Vp7X7HlStb57rG69rjcbM666a7kzkOAtEkjNIuB9iz2ej7xGBpD2JpxA4neg0R8nd6oR18TXRPeiYP4//Plqb5k1/NBuXPuh0zg3toIIMxTKdQQSTXMTzQcMXiNP0eyovFyqkPtKv/l9hlCzbc4kBG1Opu40JCRIeVMZ/wBOQBx7Lhz64GJPitVpsNzKBc/7mYLQCU3rBg+MxBQ4feIL37PH4p8//mgbjmIsyCynCpV0mB/+xoGKvlVp3zCRO85pMyVTVoSbHXvFaabvePWgCbYMwv7aHo=
  - secure: bvYppWuWQTw7LG4voOr6Ez8TcuRa696b2FEztRnzCM7JBrAKTog6lS5vW2NgvioPCk0oDu7gU0kz51dQUJz2BZgrsjkYwpTyVt65RYAur+YM84a0pQpWXBk4ro/7kAdWFX+nhMm5u9f1OMVOFi6JpAfEkotffwH94sjQHbMVUbWCuTf1DXy4yFpC5YPbRYT9S6KfWB/Abs3OZMkMWJdvoE/z1Drgi13ulMUjqUr/LAxSTvOo9ExxL/33YB2rmHySRlwUC/qcZXpcLgtl8P6Y0iE0roewrL76C/pk1DxuhwxU/uc8eNeXKefymmJ3TArK/EIv34SIv/k2MK58V8smIXsZ8pvoTD4PiCvmWyDTZyiqZ6Fmhmv7h1zxi7dfZbxwoyb8BaSab7lirjD3xC9NsbRX9gRI2+Rwq2XiM4/RrK1HmhDZhb0LzWGYuAefdereZIHeryq6zCEPSp+baTrQlrE6eTiY4EHAMhmmXuqnNrz+liCpHb2yNI2KRwc66nqpKJWOGqgwUufFwjKpgOL0sK7/Fazsu24q6CzHgygNLsCLZoVT47t7Y5Mn8IEkUy+gzlhbwgR1Yr/YaqzcJMGnljPm11SU4yEQ04VjUgVCC1WMsHukmcS3PGHdWqOuQWgBc11yOBJ+94f8rDNddQr0XxNxqThKxkBpF9MJHOlDvKA=
